apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sonar-demo
  namespace: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sonar-demo
  template:
    metadata:
      labels:
        app: java-sonar-demo
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: java-sonar-demo
        image: 831103387233.dkr.ecr.ap-south-1.amazonaws.com/java-sonar-demo:main-15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
